---
 blueprint:
  layout_path: 'config/config.json'
 runtime:
  protocol: 'http'
  ip: '127.0.0.1'
  port: '3131'
  resource_uri: '/kitops/'
 registration:
  protocol: 'http'
  ip: '15.185.91.88'
  port: '3131'
  resource_uri: '/devkit/'
